###recupero todos los items del sideBar
GET http://localHost:1234/items


###creo un nuevo item que no sea valido
POST http://localHost:1234/items
Content-Type: application/json

{
    "id": "21a250f2-469b-4eb9-a9d5-8d3d6e3a7d71",
    "name": "Paradigmas",
    "type": "como estas?",
    "color": "#F5A623",
    "parent_id": null,
    "position": 10
}

###Item valido
POST http://localHost:1234/items
Content-Type: application/json

{
    "id": "21a250f2-469b-4eb9-a9d5-8d3d6e3a7d71",
    "name": "Paradigmas",
    "type": "folder",
    "color": "#F5A623",
    "parent_id": null,
    "position": 10
}

###Renombrar un archivo
PUT http://localHost:1234/items
Content-Type: application/json

  {
    "id": "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
    "name": "Recetas cocina"

  }


###Cambiar color
PUT http://localHost:1234/items
Content-Type: application/json

  {
    "id": "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
    "color": "#cca9a9"

  }


###Borrar una carpeta que tenga hijos de varios niveles
DELETE  http://localHost:1234/items/6ba7b810-9dad-11d1-80b4-00c04fd430c8


###Borrar una archivo
DELETE  http://localHost:1234/items/ad647242-23f4-4f9e-b765-680455799767


